image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies
    # Update base env with packages from environment.yml
    # Run on initial workspace start if no prebuild available
    init: |
      conda env update --file environment.yml --prune
    # Run on every workspace start
    command: |
      pip3 install -r requirements.txt

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - ms-toolsai.jupyter
    - oderwat.indent-rainbow
    - ms-python.black-formatter
