name: teloclip
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.12
  - minimap2
  - samtools
  #- bioconda::winnowmap
  - pip
  - pip:
      - click
      - hatch
      - isort
      - numpydoc-validation
      - pandas
      - pre-commit
      - pytest
      - pytest-cov
      - ruff
