name: teloclip-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.12
  - bioconda::minimap2
  - bioconda::samtools
  - pip
  - pip:
      #- biopython
      #- regex
      #- pysam
      - black
      - setuptools_scm
      - build
      - twine
