name: teloclip
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.12
  - minimap2
  - samtools
  #- bioconda::winnowmap
  - pip
  - pip:
      #- biopython
      #- regex
      #- pysam
      - pytest
      - hatch
