name: teloclip-dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - nanoporetech # Has minimap and samtools for Apple Silicon
dependencies:
  - python >=3.12
  - minimap2
  - samtools
  #- bioconda::winnowmap
  - pip
  - pip:
      #- biopython
      #- regex
      #- pysam
      - pytest
      - build
      - twine
