#!/usr/bin/env python3
"""
Build the demo assembly used for the figures in the README and the docs.

The mock dataset under ``tests/data`` has four contigs, which is below the
eight-contig floor teloclip needs before it will call anything anomalous, so a
report built from it cannot show the flagging or the shapes the charts exist to
reveal. This generates a small assembly that does, with one contig for each
situation a reader needs to recognise:

    chr1 - chr6         ordinary linear chromosomes: moderate overhang depth,
                        overhangs a few hundred bases long at both ends
    mito                a circular contig at ordinary coverage. Circular
                        molecules always yield clipped reads at the artificial
                        break, which is why they should be excluded rather than
                        extended
    rdna_plasmid        a high-copy circular element: very deep, but the
                        overhangs are short. Deep-but-short is the signature of
                        reads drawn in from elsewhere
    chr7_rdna_array     a linear chromosome with a collapsed rDNA array at one
                        end: deep *and* long, the combination that means the
                        assembly has collapsed a repeat rather than stopped
                        short of a telomere
    chr8_long_telomere  a chromosome the assembly stopped well short of: few
                        reads, but each reaching a long way past the end. This
                        is the case extension exists to serve

Output is written to ``.plans/demo-data`` by default: a FASTA, a coordinate
sorted and indexed BAM, and the intermediate SAM. Nothing here is used by the
test suite; the integration dataset in ``tests/integration/test_data`` is
generated by the other scripts in this directory and is unaffected.

Usage
-----
    python scripts/testdata/generate_demo_assembly.py [--outdir DIR]

Requires ``samtools`` on PATH for the BAM conversion.
"""

import argparse
import pathlib
import random
import shutil
import subprocess
import sys

# Fixed so the committed figures can be regenerated byte-for-byte.
SEED = 20240817

TELOMERE = 'TTAGGG'
TELOMERE_RC = 'CCCTAA'

# (name, length, is_circular, left end spec, right end spec)
#
# An end spec is (read count, mean clip length, clip length spread) or None for
# an end with no overhang support at all, which is what an already-complete
# telomere looks like.
CONTIGS = [
    ('chr1', 40_000, False, (9, 320, 90), (11, 280, 80)),
    ('chr2', 55_000, False, (12, 300, 70), (8, 350, 110)),
    ('chr3', 32_000, False, (7, 260, 60), (10, 310, 95)),
    ('chr4', 47_000, False, (10, 340, 100), (9, 290, 75)),
    ('chr5', 38_000, False, (8, 275, 65), (12, 330, 85)),
    ('chr6', 51_000, False, (11, 295, 80), None),
    ('mito', 26_000, True, (9, 240, 55), (10, 255, 60)),
    ('rdna_plasmid', 9_000, True, (95, 150, 40), (88, 165, 45)),
    ('chr7_rdna_array', 44_000, False, (7, 300, 70), (110, 2400, 600)),
    ('chr8_long_telomere', 36_000, False, (4, 2900, 700), (5, 3100, 800)),
]

# Reads need a solid anchor to survive the default --min-anchor 100.
ANCHOR_MEAN = 900
ANCHOR_SPREAD = 250
MIN_ANCHOR = 300

# Most reads sit flush with the contig end; a few stop just short of it, which
# is what --max-break tolerates.
MAX_GAP = 12


def random_sequence(length: int, rng: random.Random) -> str:
    """
    Draw a random nucleotide sequence.

    Parameters
    ----------
    length : int
        Number of bases to generate.
    rng : random.Random
        Seeded generator, so the dataset is reproducible.

    Returns
    -------
    str
        The sequence.
    """
    return ''.join(rng.choice('ACGT') for _ in range(length))


def telomeric_tract(length: int, rng: random.Random, reverse: bool) -> str:
    """
    Build a telomere-like tract of the requested length.

    Real telomeres are not perfect repeats, so a small fraction of bases are
    mutated. Without that, motif counting on this dataset would look
    unrealistically clean.

    Parameters
    ----------
    length : int
        Length of the tract in bases.
    rng : random.Random
        Seeded generator.
    reverse : bool
        Build the reverse-complement repeat, as found reading outward from the
        left end of a contig.

    Returns
    -------
    str
        The tract, exactly ``length`` bases long.
    """
    unit = TELOMERE_RC if reverse else TELOMERE
    tract = (unit * (length // len(unit) + 1))[:length]

    # A little decay, so fuzzy matching has something to do.
    bases = list(tract)
    for index in range(len(bases)):
        if rng.random() < 0.02:
            bases[index] = rng.choice('ACGT')
    return ''.join(bases)


def revcomp(sequence: str) -> str:
    """
    Reverse complement a nucleotide sequence.

    Parameters
    ----------
    sequence : str
        Input sequence.

    Returns
    -------
    str
        The reverse complement.
    """
    return sequence.translate(str.maketrans('ACGTacgt', 'TGCAtgca'))[::-1]


def build_contigs(rng: random.Random) -> dict:
    """
    Generate the contig sequences.

    Parameters
    ----------
    rng : random.Random
        Seeded generator.

    Returns
    -------
    dict
        Mapping of contig name to sequence.
    """
    sequences = {}
    for name, length, _circular, _left, _right in CONTIGS:
        body = random_sequence(length, rng)

        # Give the linear chromosomes a short telomeric tract already assembled
        # at each end, so the overhang reads continue an existing repeat rather
        # than appearing out of unique sequence.
        head = telomeric_tract(120, rng, reverse=True)
        tail = telomeric_tract(120, rng, reverse=False)
        sequences[name] = head + body[len(head) + len(tail) :] + tail
    return sequences


def make_read(
    name: str,
    contig: str,
    contig_length: int,
    sequence: str,
    is_left: bool,
    clip_length: int,
    rng: random.Random,
) -> str:
    """
    Build one SAM record for a read overhanging a contig end.

    Parameters
    ----------
    name : str
        Read name.
    contig : str
        Reference contig name.
    contig_length : int
        Length of that contig.
    sequence : str
        The contig's sequence, used for the anchored portion of the read.
    is_left : bool
        Whether the read overhangs the left end.
    clip_length : int
        Soft-clip length in bases.
    rng : random.Random
        Seeded generator.

    Returns
    -------
    str
        A tab-separated SAM record.
    """
    anchor = max(MIN_ANCHOR, int(rng.gauss(ANCHOR_MEAN, ANCHOR_SPREAD)))
    anchor = min(anchor, contig_length // 3)

    # Most reads reach the terminal base; a few stop a little short.
    gap = 0 if rng.random() < 0.7 else rng.randint(1, MAX_GAP)

    clip = telomeric_tract(clip_length, rng, reverse=is_left)

    if is_left:
        pos = 1 + gap
        anchor_seq = sequence[pos - 1 : pos - 1 + anchor]
        cigar = f'{clip_length}S{anchor}M'
        read_seq = clip + anchor_seq
        flag = 0
    else:
        end = contig_length - gap
        pos = end - anchor + 1
        anchor_seq = sequence[pos - 1 : end]
        cigar = f'{anchor}M{clip_length}S'
        read_seq = anchor_seq + clip
        flag = 0

    return '\t'.join(
        [
            name,
            str(flag),
            contig,
            str(pos),
            '60',
            cigar,
            '*',
            '0',
            '0',
            read_seq,
            '*',
        ]
    )


def build_alignments(sequences: dict, rng: random.Random) -> list:
    """
    Generate the SAM records for every contig end.

    Parameters
    ----------
    sequences : dict
        Contig name to sequence.
    rng : random.Random
        Seeded generator.

    Returns
    -------
    list of str
        SAM alignment records, unsorted.
    """
    records = []
    for name, length, _circular, left_spec, right_spec in CONTIGS:
        sequence = sequences[name]
        for is_left, spec in ((True, left_spec), (False, right_spec)):
            if spec is None:
                continue
            count, mean_clip, spread = spec
            side = 'L' if is_left else 'R'
            for index in range(count):
                clip_length = max(20, int(rng.gauss(mean_clip, spread)))
                records.append(
                    make_read(
                        f'{name}_{side}{index:03d}',
                        name,
                        length,
                        sequence,
                        is_left,
                        clip_length,
                        rng,
                    )
                )
    return records


def write_fasta(path: pathlib.Path, sequences: dict, width: int = 80) -> None:
    """
    Write contigs to a FASTA file.

    Parameters
    ----------
    path : pathlib.Path
        Destination.
    sequences : dict
        Contig name to sequence.
    width : int, optional
        Line wrap width (default: 80).
    """
    with open(path, 'w') as handle:
        for name, _length, _circular, _left, _right in CONTIGS:
            sequence = sequences[name]
            handle.write(f'>{name}\n')
            for start in range(0, len(sequence), width):
                handle.write(sequence[start : start + width] + '\n')


def write_sam(path: pathlib.Path, records: list) -> None:
    """
    Write the SAM file, header included.

    Parameters
    ----------
    path : pathlib.Path
        Destination.
    records : list of str
        Alignment records.
    """
    with open(path, 'w') as handle:
        handle.write('@HD\tVN:1.6\tSO:unsorted\n')
        for name, length, _circular, _left, _right in CONTIGS:
            handle.write(f'@SQ\tSN:{name}\tLN:{length}\n')
        handle.write('@PG\tID:generate_demo_assembly\tPN:generate_demo_assembly\n')
        for record in records:
            handle.write(record + '\n')


def run(cmd: list) -> None:
    """
    Run a subprocess, failing loudly.

    Parameters
    ----------
    cmd : list of str
        Command and arguments.

    Raises
    ------
    SystemExit
        If the command fails.
    """
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f'{" ".join(cmd)} failed:\n{result.stderr}')


def main() -> None:
    """Generate the demo assembly and its indexed alignments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--outdir',
        type=pathlib.Path,
        default=pathlib.Path('.plans/demo-data'),
        help='Directory to write the demo dataset to.',
    )
    args = parser.parse_args()

    if shutil.which('samtools') is None:
        sys.exit('samtools is required to build the BAM but was not found on PATH.')

    args.outdir.mkdir(parents=True, exist_ok=True)
    rng = random.Random(SEED)

    sequences = build_contigs(rng)
    records = build_alignments(sequences, rng)

    fasta = args.outdir / 'demo_assembly.fasta'
    sam = args.outdir / 'demo_overhangs.sam'
    bam = args.outdir / 'demo_overhangs.bam'

    write_fasta(fasta, sequences)
    write_sam(sam, records)

    run(['samtools', 'faidx', str(fasta)])
    run(['samtools', 'sort', '-o', str(bam), str(sam)])
    run(['samtools', 'index', str(bam)])

    print(f'{len(CONTIGS)} contigs, {len(records)} overhang reads')
    print(f'  {fasta}')
    print(f'  {bam}')


if __name__ == '__main__':
    main()
